### ISSUE TITLE
KeyError with non-str key

### ISSUE THREAD

**Issue by alexmojaki** [aroberge/friendly-traceback#102]
```python
import inspect

from friendly_traceback.info_specific import get_likely_cause

try:
    {}[0]
except KeyError as e:
    get_likely_cause(type(e), e, {}, inspect.currentframe())

Traceback (most recent call last):
  File "/home/alex/.config/JetBrains/PyCharm2020.2/scratches/scratch_874.py", line 8, in <module>
    get_likely_cause(type(e), e, {}, inspect.currentframe())
  File "/home/alex/.cache/pypoetry/virtualenvs/book-E12DIahb-py3.8/src/friendly-traceback/friendly_traceback/info_specific.py", line 20, in get_likely_cause
    cause = get_cause[etype.__name__](value, info, frame)
  File "/home/alex/.cache/pypoetry/virtualenvs/book-E12DIahb-py3.8/src/friendly-traceback/friendly_traceback/info_specific.py", line 109, in key_error
    ).format(key_name=str(value).split("'")[1])
IndexError: list index out of range
```

I suggest:

1. Not referring to it as 'the name of the key'
2. Showing the repr without stripping quotes. Not only will this not break, it will distinguish between `1` and `"1"`.

```python
    return _(
        "In your program, the key\n"
        "that cannot be found is `{key_name!r}`.\n"
    ).format(key_name=value.args[0])
```

**Comment by aroberge** [comment]
Good suggestions, thanks.
