### ISSUE TITLE
Syntax error inside f-string

### ISSUE THREAD

**Issue by alexmojaki** [aroberge/friendly-traceback#115]
TIL that f-strings make their own little 'file' which leads to different looking syntax errors. If I run `f"a {x y} b"` in normal Python it outputs:

```
  File "<fstring>", line 1
    (x y)
       ^
SyntaxError: invalid syntax
```

This breaks friendly-traceback:

```python
import sys
from friendly_traceback.core import get_traceback_info

try:
    eval('f"a {x y} b"')
except:
    get_traceback_info(*sys.exc_info(), debug=True)
```

```pytb
    WARNING: Internal error caught in process_syntax_error()
Traceback (most recent call last):
  File "/home/alex/.config/JetBrains/PyCharm2020.2/scratches/scratch_955.py", line 5, in <module>
    eval('f"a {x y} b"')
  File "<fstring>", line 1
    (x y)
       ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alex/.config/JetBrains/PyCharm2020.2/scratches/scratch_955.py", line 7, in <module>
    get_traceback_info(*sys.exc_info(), debug=True)
  File "/home/alex/.cache/pypoetry/virtualenvs/book-E12DIahb-py3.8/lib/python3.8/site-packages/friendly_traceback/core.py", line 109, in get_traceback_info
    return process_syntax_error(etype, value, info, debug)
  File "/home/alex/.cache/pypoetry/virtualenvs/book-E12DIahb-py3.8/lib/python3.8/site-packages/friendly_traceback/core.py", line 151, in process_syntax_error
    analyze_syntax.set_cause_syntax(etype, value, info)  # [3]
  File "/home/alex/.cache/pypoetry/virtualenvs/book-E12DIahb-py3.8/lib/python3.8/site-packages/friendly_traceback/syntax_errors/analyze_syntax.py", line 19, in set_cause_syntax
    get_likely_cause(etype, value, info)
  File "/home/alex/.cache/pypoetry/virtualenvs/book-E12DIahb-py3.8/lib/python3.8/site-packages/friendly_traceback/syntax_errors/analyze_syntax.py", line 33, in get_likely_cause
    cause = syntax_error_cause(value, info)
  File "/home/alex/.cache/pypoetry/virtualenvs/book-E12DIahb-py3.8/lib/python3.8/site-packages/friendly_traceback/syntax_errors/analyze_syntax.py", line 115, in syntax_error_cause
    return _find_likely_cause(source_lines, linenumber, message, offset, info)
  File "/home/alex/.cache/pypoetry/virtualenvs/book-E12DIahb-py3.8/lib/python3.8/site-packages/friendly_traceback/syntax_errors/analyze_syntax.py", line 126, in _find_likely_cause
    offending_line = source_lines[linenumber - 1]
IndexError: list index out of range
```

**Comment by aroberge** [comment]
Wow ... weird one.  I'll try to fix it this morning as well.

**Comment by alexmojaki** [comment]
I don't understand the 'fix'. There's no file `<fstring>` but the inner code is still available in full in the message, so it should be possible to see what's wrong with the contents of `{}`.

**Comment by aroberge** [comment]
(Using screen captures as I cannot copy from the terminal I use :-/ )

I don't see the code in the message using Python 3.8

![image](https://user-images.githubusercontent.com/629698/98126455-000c6880-1e8c-11eb-8f75-8049ee7dd29d.png)

However, I see that 3.9 provides a better message, which, when a file is named, allows me to find the line with the problem.

![image](https://user-images.githubusercontent.com/629698/98127301-e91a4600-1e8c-11eb-9003-cc89609b0466.png)

Reopening this with the goal of attempting to provide an error analysis when possible.

**Comment by alexmojaki** [comment]
Look at the normal python traceback, not friendly traceback.

```
$ python3.6 -c 'f"{x y}"'
  File "<fstring>", line 1
    (x y)
       ^
SyntaxError: invalid syntax
$ python3.7 -c 'f"{x y}"'
  File "<fstring>", line 1
    (x y)
       ^
SyntaxError: invalid syntax
$ python3.8 -c 'f"{x y}"'
  File "<fstring>", line 1
    (x y)
       ^
SyntaxError: invalid syntax
$ python3.9 -c 'f"{x y}"'
  File "<string>", line 1
    (x y)
       ^
SyntaxError: f-string: invalid syntax
```

**Comment by aroberge** [comment]
Yes, I just saw the difference trying here.  Here's a different test (documenting for when I try to fix it).
![image](https://user-images.githubusercontent.com/629698/98128098-da805e80-1e8d-11eb-8bfb-0a8145eebf36.png)

I construct the "friendly traceback" by using `inspect.getinnerframes`.  It seems that It does not give me exactly the same information as the original Python traceback. Normally, there is an alternance of filename/line in the traceback, but on the screen capture, you can see that I have two "files" in a row (one of which is the `<fstring>`) without a line of code in between.

I will need to handle this case differently, to ensure that I extract all the available information.

**Comment by aroberge** [comment]
Reopening issue as it is not analyzed properly when using python 3.9+
