### ISSUE TITLE
Error getting cause of attribute error for built in module

### ISSUE THREAD

**Issue by alexmojaki** [aroberge/friendly-traceback#116]
```python
import sys
from friendly_traceback.core import get_traceback_info

try:
    sys.foo
except:
    get_traceback_info(*sys.exc_info(), debug=True)
```

```pytb
Traceback (most recent call last):
  File "/home/alex/.config/JetBrains/PyCharm2020.2/scratches/scratch_958.py", line 5, in <module>
    sys.foo
AttributeError: module 'sys' has no attribute 'foo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alex/.config/JetBrains/PyCharm2020.2/scratches/scratch_958.py", line 7, in <module>
    get_traceback_info(*sys.exc_info(), debug=True)
  File "/home/alex/.cache/pypoetry/virtualenvs/book-E12DIahb-py3.8/lib/python3.8/site-packages/friendly_traceback/core.py", line 129, in get_traceback_info
    info_specific.get_likely_cause(etype, value, info, frame)  # [3]
  File "/home/alex/.cache/pypoetry/virtualenvs/book-E12DIahb-py3.8/lib/python3.8/site-packages/friendly_traceback/info_specific.py", line 19, in get_likely_cause
    cause = get_cause[etype.__name__](value, info, frame)
  File "/home/alex/.cache/pypoetry/virtualenvs/book-E12DIahb-py3.8/lib/python3.8/site-packages/friendly_traceback/info_specific.py", line 46, in _attribute_error
    return attribute_error.get_cause(value, info, frame)
  File "/home/alex/.cache/pypoetry/virtualenvs/book-E12DIahb-py3.8/lib/python3.8/site-packages/friendly_traceback/runtime_errors/attribute_error.py", line 19, in get_cause
    return attribute_error_in_module(match.group(1), match.group(2), info, frame)
  File "/home/alex/.cache/pypoetry/virtualenvs/book-E12DIahb-py3.8/lib/python3.8/site-packages/friendly_traceback/runtime_errors/attribute_error.py", line 85, in attribute_error_in_module
    mod_path = shorten_path(mod.__file__)
AttributeError: module 'sys' has no attribute '__file__'

    WARNING: Internal error caught in get_likely_cause().
``

**Comment by aroberge** [comment]
Thanks for the report!
