### ISSUE TITLE
Contest #141: Unbound Local after deletion

### ISSUE THREAD

**Issue by Carreau** [aroberge/friendly-traceback#142]
```
$ python -m friendly_traceback foo.py

╭──────────────────────────────────────── Python exception ─────────────────────────────────────────╮
│ Traceback (most recent call last):                                                                │
│   File "foo.py", line 8, in <module>                                                              │
│     f()                                                                                           │
│   File "foo.py", line 4, in f                                                                     │
│     print(x)                                                                                      │
│ UnboundLocalError: local variable 'x' referenced before assignment                                │
│                                                                                                   │
│ In Python, variables that are used inside a function are known as local variables. Before they    │
│ are used, they must be assigned a value. A variable that is used before it is assigned a value is │
│ assumed to be defined outside that function; it is known as a global (or sometimes nonlocal)      │
│ variable. You cannot assign a value to such a global variable inside a function without first     │
│ indicating to Python that this is a global variable, otherwise you will see an UnboundLocalError. │
│                                                                                                   │
│ Execution stopped on line 8 of file 'foo.py'.                                                     │
│                                                                                                   │
│         6:                                                                                        │
│         7: if __name__ == "__main__":                                                             │
│     --> 8:     f()                                                                                │
│                                                                                                   │
│     f: <function f>                                                                               │
│                                                                                                   │
│ Exception raised on line 4 of file 'foo.py'.                                                      │
│                                                                                                   │
│        2:     x = 1                                                                               │
│        3:     del x                                                                               │
│     -->4:     print(x)                                                                            │
│                                                                                                   │
│     print: <builtin function print>                                                               │
╰───────────────────────────────────────────────────────────────────────────────────────────────────╯
$ cat foo.py
def f():
    x = 1
    del x
    print(x)


if __name__ == "__main__":
    f()
```

I can't claim discovering it; it was pointed out by Raymond Hettinger in one of PyBay keynote. 

The above example is clearly obvious, but you can find variants if there are complex branching that trigger the del; or similarly if a branch was not taken and would have declared a variable.

**Comment by aroberge** [comment]
As in issue 142, Friendly-traceback does recognize the message provided by Python for this error.
