### ISSUE TITLE
Incorrect "The opening parenthesis ( on line 1 is not closed"

### ISSUE THREAD

**Issue by tomerv** [aroberge/friendly-traceback#154]
The explanation is a bit misleading.

```
┌───────────────────────────────────────────────── Python exception ──────────────────────────────────────────────────┐
│ Traceback (most recent call last):                                                                                  │
│   File "test.py", line 1                                                                                            │
│     lambda (t): True                                                                                                │
│            ^                                                                                                        │
│ SyntaxError: invalid syntax                                                                                         │
│                                                                                                                     │
│ A SyntaxError occurs when Python cannot understand your code.                                                       │
│                                                                                                                     │
│ Python could not understand the code in the file 'test.py' beyond the location indicated by --> and ^.              │
│                                                                                                                     │
│     -->1: lambda (t): True                                                                                          │
│                  ^                                                                                                  │
│                                                                                                                     │
│ The opening parenthesis ( on line 1 is not closed.                                                                  │
│                                                                                                                     │
│ 1: lambda (t): True                                                                                                 │
│           |                                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by tomerv** [comment]
Also this one, probably the same issue

```
┌───────────────────────────────────────────────── Python exception ──────────────────────────────────────────────────┐
│ Traceback (most recent call last):                                                                                  │
│   File "test.py", line 1                                                                                            │
│     def foo(1):                                                                                                     │
│             ^                                                                                                       │
│ SyntaxError: invalid syntax                                                                                         │
│                                                                                                                     │
│ A SyntaxError occurs when Python cannot understand your code.                                                       │
│                                                                                                                     │
│ Python could not understand the code in the file 'test.py' beyond the location indicated by --> and ^.              │
│                                                                                                                     │
│     -->1: def foo(1):                                                                                               │
│                   ^                                                                                                 │
│                                                                                                                     │
│ The opening parenthesis ( on line 1 is not closed.                                                                  │
│                                                                                                                     │
│ 1: def foo(1):                                                                                                      │
│           |                                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by aroberge** [comment]
The first one has already been reported (https://github.com/aroberge/friendly-traceback/issues/152#issuecomment-764686444). I consider the second one to be a different issue, and a valid entry.
