### ISSUE TITLE
A few string related errors

### ISSUE THREAD

**Issue by gdementen** [aroberge/friendly-traceback#155]
These are all errors I have seen people actually do while teaching Python to beginner programmers.

They are probably not valid contest entry because friendly-traceback does tells something which is correct but it could probably be improved nevertheless.

```python
>>> s = "a'

Traceback (most recent call last):
  File "<friendly-console:3>", line 1
    s = "a'
           ^
SyntaxError: EOL while scanning string literal

Did you forget a closing quote?
```
This one I have also made it several times myself:

```python
>>> s = "a\"

Traceback (most recent call last):
  File "<friendly-console:5>", line 1
    s = "a\"
            ^
SyntaxError: EOL while scanning string literal

Did you forget a closing quote?
```

And this one confused the hell out of me (because I thought that all \ were ignored in raw strings):

```python
>>> s = r"a\"

Traceback (most recent call last):
  File "<friendly-console:5>", line 1
    s = r"a\"
            ^
SyntaxError: EOL while scanning string literal

Did you forget a closing quote?
```

**Comment by aroberge** [comment]
Thanks for this submission. Note that you can get more information by asking `why()`:
```
>>> why()

You starting writing a string with a single or double quote but never
ended the string with another quote on that line.
```
I agree that identifying the final unscaped `\`  could definitely be an improvement; so I will consider this particular case to be a valid entry for the contest.

**Comment by aroberge** [comment]
Now identifying unescaped backslash.
```pytb
>>> a = "ab\"

Traceback (most recent call last):
  File "<friendly-console:3>", line 1
    a = "ab\"
             ^
SyntaxError: EOL while scanning string literal

Did you forget to escape a backslash character?
>>> why()

You starting writing a string with a single or double quote but never
ended the string with another quote on that line. Perhaps you meant to
write the backslash character, \ as the last character in the string and
forgot that you needed to escape it by writing two \ in a row.
```
