### ISSUE TITLE
SyntaxError when using leading zeros in decimal integer literals

### ISSUE THREAD

**Issue by Dominik1123** [aroberge/friendly-traceback#160]
```
$ python -m friendly_traceback

Friendly Console version 0.2.19. [Python version: 3.9.0]

>>> x = 01

Traceback (most recent call last):                                                                                                                                 
  File "<friendly-console:1>", line 1                                                                                                                              
    x = 01                                                                                                                                                         
         ^                                                                                                                                                         
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers                                                      

Did you forget something between 0 and 1?
```

The hint in this case is misleading, as most likely the intent was to use a leading zero in the literal.

Here's a popular [SO question](https://stackoverflow.com/questions/31447694/why-does-python-3-allow-00-as-a-literal-for-0-but-not-allow-01-as-a-literal).

---

There's also a version that involves underscore separation:

```
$ python -m friendly_traceback

Friendly Console version 0.2.19. [Python version: 3.9.0]

>>> x = 000_123_456

Traceback (most recent call last):                                                                                                                                 
  File "<friendly-console:1>", line 1                                                                                                                              
    x = 000_123_456                                                                                                                                                
                  ^                                                                                                                                                
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers                                                      

Perhaps you forgot a multiplication operator, 000 * _123_456.
```

Again the intent was most likely to use leading zeros (at least multiplication by literal `0` wouldn't be very useful).

**Comment by aroberge** [comment]
Ok - and given the StackOverflow reference, this is a submission worth two normal ones.
