### ISSUE TITLE
SyntaxError: f-string expression part cannot include a backslash

### ISSUE THREAD

**Issue by Dominik1123** [aroberge/friendly-traceback#163]
```
$ python -m friendly_traceback

Friendly Console version 0.2.19. [Python version: 3.9.0]

>>> names = ['foo', 'bar']
>>> f'{"\n".join(names)}'

Traceback (most recent call last):                                                                                                                                 
  File "<friendly-console:2>", line 1                                                                                                                              
    f'{"\n".join(names)}'                                                                                                                                          
                         ^                                                                                                                                         
SyntaxError: f-string expression part cannot include a backslash
```

Basically the Python error message says it all, but perhaps it would be useful to include a hint on how to work around this issue (e.g. assigning `newline = '\n'; f'{newline.join(names)}'`).

This seems to be also quite popular on [StackOverflow](https://stackoverflow.com/questions/44780357/how-to-use-newline-n-in-f-string-to-format-output-in-python-3-6).

**Comment by aroberge** [comment]
Normally, I would not consider f-string cases as I refer to the documentation. Basically, the syntax is somewhat idiosynchratic and there's no way that I can consider them a high priority. However, the message is rather distinctive (not `f-string: invalid syntax`) so that I should definitely cover it. And, given the StackOverflow reference, it counts doubly.

**Comment by aroberge** [comment]
Fixed. Example:
```

╭────────────────────────── Python exception ───────────────────────────╮
│Traceback (most recent call last):                                     │
│  File "ignore.py", line 2                                             │
│    print(f"{'\n'.join(names)}")                                       │
│                               ^                                       │
│SyntaxError: f-string expression part cannot include a backslash       │
│                                                                       │
│A SyntaxError occurs when Python cannot understand your code.          │
│                                                                       │
│Python could not understand the code in the file 'ignore.py' beyond the│
│location indicated by --> and ^.                                       │
│                                                                       │
│       1: names = ['a', 'b']                                           │
│    -->2: print(f"{'\n'.join(names)}")                                 │
│                                     ^                                 │
│                                                                       │
│You have written an f-string whose content {...} includes a backslash; │
│this is not allowed. Perhaps you can replace the part that contains a  │
│backslash by some variable. For example, suppose that you have an      │
│f-string like:                                                         │
│                                                                       │
│f"{... 'hello\n' ...}"                                                 │
│                                                                       │
│you could write this as                                                │
│                                                                       │
│hello = '\hello\n'                                                     │
│f"{... hello ...}"                                                     │
╰───────────────────────────────────────────────────────────────────────╯
```
