### ISSUE TITLE
KeyError for subscript in format string (similarly for attribute access)

### ISSUE THREAD

**Issue by Dominik1123** [aroberge/friendly-traceback#164]
```
$ python -m friendly_traceback

Friendly Console version 0.2.19. [Python version: 3.9.0]

>>> template = '{foo[0]}'
>>> template.format(foo=dict(a=1))

Traceback (most recent call last):                                                                                                                                 
  File "<friendly-console:2>", line 1, in <module>                                                                                                                 
    template.format(foo=dict(a=1))                                                                                                                                 
KeyError: 0
```

I'm not sure how easy it is to recognize and to explain this one, but a note about the fact that the format string expected something with key `0` would be helpful I guess.

There exist other variants, with for example attribute access, as well:

```
$ python -m friendly_traceback

Friendly Console version 0.2.19. [Python version: 3.9.0]

>>> template = '{number.real}, {number.imag}'
>>> template.format(number='123')

Traceback (most recent call last):                                                                                                                                 
  File "<friendly-console:2>", line 1, in <module>                                                                                                                 
    template.format(number='123')                                                                                                                                  
AttributeError: 'str' object has no attribute 'real'
```

**Comment by aroberge** [comment]
I'm going to consider the second one as valid, and being the prototype for all `str.format` cases.

**Comment by Dominik1123** [comment]
In some circumstances the first one can be difficult (non-obvious) to debug too. Here's a better example:

```
>>> template = '{foo[a]}, {bar}'
>>> template.format(foo=dict(b=1), bar=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'a'
>>> template.format(foo=dict(a=1), bar=2)
'1, 2'
```

The user might think that the `template` string expects a top-level object `a`, while it's the `foo` object that should have this key. For such short template strings it might be obvious but if they're longer and contain more keys then it might be difficult. It looks similar as if `bar` was omitted:

```
>>> template.format(foo=dict(a=1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'bar'
```

So the `KeyError` doesn't distinguish between the format string and the passed objects. So it would helpful if the hint could.

**Comment by aroberge** [comment]
These cases with string formatting are beyond the scope of Friendly-traceback as they would require implementing parsing of string formatting to extract the information required for further processing.
