### ISSUE TITLE
Trying to subscript `globals` or `locals` directly

### ISSUE THREAD

**Issue by Dominik1123** [aroberge/friendly-traceback#166]
```
$ python -m friendly_traceback

Friendly Console version 0.2.19. [Python version: 3.9.0]

>>> x = 1
>>> globals['x']

Traceback (most recent call last):                                                                                                                                 
  File "<friendly-console:2>", line 1, in <module>                                                                                                                 
    globals['x']                                                                                                                                                   
TypeError: 'builtin_function_or_method' object is not subscriptable                                                                                                

Did you mean globals('x')?                                                                                                                                          
>>> globals('x')

Traceback (most recent call last):                                                                                                                                 
  File "<friendly-console:3>", line 1, in <module>                                                                                                                 
    globals('x')                                                                                                                                                   
TypeError: globals() takes no arguments (1 given)
```

Most likely the expectation was that `globals` *is* the dict and hence the intention was to do `globals()['x']`.

**Comment by aroberge** [comment]
As mentioned in another comment, TypeError are not included.

**Comment by Dominik1123** [comment]
No problem, I thought it might be useful to special case `locals` and `globals` in this case.

**Comment by aroberge** [comment]
Moved to TypeError cases issue.
