### ISSUE TITLE
NameError from list comprehension that refers to another name in the class definition 

### ISSUE THREAD

**Issue by Dominik1123** [aroberge/friendly-traceback#170]
If there is a way to provide a hint about class scope for the following example, I think it would be very helpful (judging from the popularity on [StackOverflow](https://stackoverflow.com/questions/13905741/accessing-class-variables-from-a-list-comprehension-in-the-class-definition)):

```
$ python -m friendly_traceback

Friendly Console version 0.2.19. [Python version: 3.9.0]

>>> class Foo:
...     n = 5
...     x = [i+n for i in range(5)]
... 

Traceback (most recent call last):                                                                                                                                                       
  File "<friendly-console:1>", line 1, in <module>                                                                                                                                       
    class Foo:                                                                                                                                                                           
  File "<friendly-console:1>", line 3, in Foo                                                                                                                                            
    x = [i+n for i in range(5)]                                                                                                                                                          
  File "<friendly-console:1>", line 3, in <listcomp>                                                                                                                                     
    x = [i+n for i in range(5)]                                                                                                                                                          
NameError: name 'n' is not defined
```

**Comment by aroberge** [comment]
I will have to explore ... but I don't think it is possible, based on the answers given on StackOverflow.  Given the frame where the exception is raised, I look at the local, global and nonlocal scopes, listing variables encountered. Since I don't see `n` listed when looking at the full explanation, I have the sneaking suspicion that it is not possible to identify `n`.  I'll have to do a bit of digging - I'll leave this case undetermined for now.

**Comment by aroberge** [comment]
Closing: there is no possibility of getting information about class scope.
