### ISSUE TITLE
SyntaxError: annotated name '...' can't be global

### ISSUE THREAD

**Issue by tomerv** [aroberge/friendly-traceback#171]
file contents:

```
def foo():
    global x
    x:int = 1

x = 0
foo()
```

Result:

```
┌───────────────────────────────────────────────── Python exception ──────────────────────────────────────────────────┐
│ Traceback (most recent call last):                                                                                  │
│   File "test.py", line 3                                                                                            │
│     x:int = 1                                                                                                       │
│    ^                                                                                                                │
│ SyntaxError: annotated name 'x' can't be global                                                                     │
│                                                                                                                     │
│ Did you forget something between x and x?                                                                           │
│                                                                                                                     │
│ A SyntaxError occurs when Python cannot understand your code.                                                       │
│                                                                                                                     │
│ Python could not understand the code in the file 'test.py' beyond the location indicated by --> and ^.              │
│                                                                                                                     │
│        1: def foo():                                                                                                │
│        2:     global x                                                                                              │
│     -->3:     x:int = 1                                                                                             │
│              ^                                                                                                      │
│                                                                                                                     │
│ Python gave us the following informative message about the possible cause of the error:                             │
│                                                                                                                     │
│ annotated name 'x' can't be global                                                                                  │
│                                                                                                                     │
│ However, I do not recognize this information and I have to guess what caused the problem, but I might be wrong.     │
│                                                                                                                     │
│ Python indicates that the error is caused by x written immediately after x. Perhaps you meant to insert an operator │
│ like +; -; *; "," between x and x. The following lines of code would not cause any SyntaxError:                     │
│                                                                                                                     │
│ x:int = 1                                                                                                           │
│ x:int = 1                                                                                                           │
│ x:int = 1                                                                                                           │
│ x:int = 1                                                                                                           │
│                                                                                                                     │
│ Note: these are just some of the possible choices and that some of them might raise other types of exceptions.      │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by tomerv** [comment]
Related issue:

```
def foo():
    global x
    x = 1

x:int = 0
foo()
```

However, this is a bug in CPython - see https://bugs.python.org/issue34939

The result:

```
┌───────────────────────────────────────────────── Python exception ──────────────────────────────────────────────────┐
│ Traceback (most recent call last):                                                                                  │
│   File "test.py", line 5                                                                                            │
│     x:int = 0                                                                                                       │
│    ^                                                                                                                │
│ SyntaxError: annotated name 'x' can't be global                                                                     │
│                                                                                                                     │
│ Did you forget something between 1 and x?                                                                           │
│                                                                                                                     │
│ A SyntaxError occurs when Python cannot understand your code.                                                       │
│                                                                                                                     │
│ Python could not understand the code in the file 'test.py' beyond the location indicated by --> and ^.              │
│                                                                                                                     │
│        1: def foo():                                                                                                │
│        2:     global x                                                                                              │
│        3:     x = 1                                                                                                 │
│        4:                                                                                                           │
│     -->5: x:int = 0                                                                                                 │
│          ^                                                                                                          │
│                                                                                                                     │
│ Python gave us the following informative message about the possible cause of the error:                             │
│                                                                                                                     │
│ annotated name 'x' can't be global                                                                                  │
│                                                                                                                     │
│ However, I do not recognize this information and I have to guess what caused the problem, but I might be wrong.     │
│                                                                                                                     │
│ Python indicates that the error is caused by 1 written immediately after x. Perhaps you meant to insert an operator │
│ like +; -; *; "," between 1 and x. The following lines of code would not cause any SyntaxError:                     │
│                                                                                                                     │
│ x:int = 0                                                                                                           │
│ x:int = 0                                                                                                           │
│ x:int = 0                                                                                                           │
│ x:int = 0                                                                                                           │
│                                                                                                                     │
│ Note: these are just some of the possible choices and that some of them might raise other types of exceptions.      │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by aroberge** [comment]
This is definitely a valid entry as the message is not recognized. So, it is most definitely a valid entry.  I see that the second case only shows up for Python 3.6 and 3.7. 

The fact that four identical lines are shown as valid suggestions is a bug in Friendly-traceback itself, the first one associated with any issue filed for this contest. I'm really, really puzzled as to how such an output can be produced. I'll have to figure out the cause of it as I likely won't be able to reproduce it after I add the `annotated name '...' can't be global` to the list of known messages with associated explanation.

**Comment by tomerv** [comment]
You excluded type annotations from the contest, be whatever you decide. So far I'm having fun finding interesting errors.

**Comment by aroberge** [comment]
I do appreciate looking for interesting errors. When I indicated that type annotations were excluded, it was because my ad-hoc method of figuring possible fixes for SyntaxErrors could not deal with the additional complications caused by the particular syntax used for type annotations.  However, Friendly-traceback should (eventually) definitely be able to recognize all error messages. Furthermore, you uncovered what I consider to be a bug in Friendly-traceback itself, something I really, really appreciate.

**Comment by aroberge** [comment]
Fixed; test case added.
