### ISSUE TITLE
SyntaxError attempting to assign to keyword

### ISSUE THREAD

**Issue by Dominik1123** [aroberge/friendly-traceback#176]
```
$ python -m friendly_traceback

Friendly Console version 0.2.19. [Python version: 3.9.0]

>>> else = 1

Traceback (most recent call last):                                                                          
  File "<friendly-console:1>", line 1                                                                       
    else = 1                                                                                                
    ^                                                                                                       
SyntaxError: invalid syntax                                                                                 

>>> why()

Currently, I cannot guess the likely cause of this error. Try to examine closely the line indicated as well  
as the line immediately above to see if you can identify some misspelled word, or missing symbols, like (, ),
[, ], :, etc.                                                                                                

Unless your code uses type annotations, which are beyond our scope, you might want to report this case to    
https://github.com/aroberge/friendly-traceback/issues                                                        
```

It works for some other keywords though, e.g.:

```
>>> def = 1

Traceback (most recent call last):                                                                          
  File "<friendly-console:3>", line 1                                                                       
    def = 1                                                                                                 
        ^                                                                                                   
SyntaxError: invalid syntax                                                                                 

>>> why()

You were trying to assign a value to the Python keyword def. This is not allowed.
```

**Comment by aroberge** [comment]
This is weird.  Looking closely, I see that `else` is identified as problematic in the first case, and `=` in the second. I suspect that other cases exist (for example `in = 1`); I will have to fix this.
