### ISSUE TITLE
SyntaxError when attempting to `del` a keyword, literal, expression

### ISSUE THREAD

**Issue by Dominik1123** [aroberge/friendly-traceback#178]
For most cases like `del None`, `del 1`, `del x**2` the Python error message basically says it all:

```
$ echo "del None" > test.py && python -m friendly_traceback test.py

╭──────────────────────────────────────────── Python exception ─────────────────────────────────────────────╮
│ Traceback (most recent call last):                                                                        │
│   File "test.py", line 1                                                                                  │
│     del None                                                                                              │
│         ^                                                                                                 │
│ SyntaxError: cannot delete None                                                                           │
│                                                                                                           │
│ A SyntaxError occurs when Python cannot understand your code.                                             │
│                                                                                                           │
│ Python could not understand the code in the file 'test.py' beyond the location indicated by --> and ^.    │
│                                                                                                           │
│     -->1: del None                                                                                        │
│               ^                                                                                           │
│                                                                                                           │
│ Currently, I cannot guess the likely cause of this error. Try to examine closely the line indicated as    │
│ well as the line immediately above to see if you can identify some misspelled word, or missing symbols,   │
│ like (, ), [, ], :, etc.                                                                                  │
│                                                                                                           │
│ Unless your code uses type annotations, which are beyond our scope, you might want to report this case to │
│ https://github.com/aroberge/friendly-traceback/issues                                                     │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

For others however the guess that is made doesn't seem to be correct:

```
$ echo "del [1]" > test.py && python -m friendly_traceback test.py

╭──────────────────────────────────────────── Python exception ─────────────────────────────────────────────╮
│ Traceback (most recent call last):                                                                        │
│   File "test.py", line 1                                                                                  │
│     del [1]                                                                                               │
│          ^                                                                                                │
│ SyntaxError: cannot delete literal                                                                        │
│                                                                                                           │
│ A SyntaxError occurs when Python cannot understand your code.                                             │
│                                                                                                           │
│ Python could not understand the code in the file 'test.py' beyond the location indicated by --> and ^.    │
│                                                                                                           │
│     -->1: del [1]                                                                                         │
│                ^                                                                                          │
│                                                                                                           │
│ Python gave us the following informative message about the possible cause of the error:                   │
│                                                                                                           │
│ cannot delete literal                                                                                     │
│                                                                                                           │
│ However, I do not recognize this information and I have to guess what caused the problem, but I might be  │
│ wrong.                                                                                                    │
│                                                                                                           │
│ The opening square bracket [ on line 1 is not closed.                                                     │
│                                                                                                           │
│ 1: del [1]                                                                                                │
│        |                                                                                                  │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

I'm not sure it's worth covering this, it could occur if this was intended to be a subscript (e.g. `del x[1]`) but then it should be pretty obvious what went wrong.

**Comment by aroberge** [comment]
I need to add these two error messages given by Python; I want to be sure that when Python identifies a potential cause of an error, I can properly recognize it.

In the second case, in the latest version (not uploaded to Pypi), I no longer give the incorrect explanation about a bracket not being closed (this was a bug that I have fixed), but I still don't provide an explanation.
