### ISSUE TITLE
SyntaxError Using slice syntax outside of subscripts

### ISSUE THREAD

**Issue by Dominik1123** [aroberge/friendly-traceback#180]
```
$ echo "second_to_third = 1:3" > test.py && python -m friendly_traceback test.py

╭────────────────────────────────────────────────────── Python exception ──────────────────────────────────────────────────────╮
│ Traceback (most recent call last):                                                                                           │
│   File "test.py", line 1                                                                                                     │
│     second_to_third = 1:3                                                                                                    │
│                        ^                                                                                                     │
│ SyntaxError: invalid syntax                                                                                                  │
│                                                                                                                              │
│ A SyntaxError occurs when Python cannot understand your code.                                                                │
│                                                                                                                              │
│ Python could not understand the code in the file 'test.py' beyond the location indicated by --> and ^.                       │
│                                                                                                                              │
│     -->1: second_to_third = 1:3                                                                                              │
│                              ^                                                                                               │
│                                                                                                                              │
│ Currently, I cannot guess the likely cause of this error. Try to examine closely the line indicated as well as the line      │
│ immediately above to see if you can identify some misspelled word, or missing symbols, like (, ), [, ], :, etc.              │
│                                                                                                                              │
│ Unless your code uses type annotations, which are beyond our scope, you might want to report this case to                    │
│ https://github.com/aroberge/friendly-traceback/issues                                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

$ echo "every_other = ::2" > test.py && python -m friendly_traceback test.py

╭────────────────────────────────────────────────────── Python exception ──────────────────────────────────────────────────────╮
│ Traceback (most recent call last):                                                                                           │
│   File "test.py", line 1                                                                                                     │
│     every_other = ::2                                                                                                        │
│                   ^                                                                                                          │
│ SyntaxError: invalid syntax                                                                                                  │
│                                                                                                                              │
│ A SyntaxError occurs when Python cannot understand your code.                                                                │
│                                                                                                                              │
│ Python could not understand the code in the file 'test.py' beyond the location indicated by --> and ^.                       │
│                                                                                                                              │
│     -->1: every_other = ::2                                                                                                  │
│                         ^                                                                                                    │
│                                                                                                                              │
│ You cannot have these two operators, = and :, following each other. Perhaps you wrote one of them by mistake or forgot to    │
│ write something between them.                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

Judging from [this SO question](https://stackoverflow.com/questions/10573485/slicing-a-list-using-a-variable-in-python) it seems to be something that people frequently search for (technically, in this question the OP attempted to use a string, i.e. `"::2"`, but there's also [this duplicate](https://stackoverflow.com/questions/10573485/slicing-a-list-using-a-variable-in-python) where plain `2:4` was attempted).

**Comment by aroberge** [comment]
While it is definitely an interesting example, it is not one that can reasonably be thought of consisting of a single mistake (i.e. something that a program like Friendly-traceback could identify as consisting of a single token error).

**Comment by Dominik1123** [comment]
It can result from a single token error, but I agree with you that it is very unlikely: if the user wanted to type `x[::2]` but accidentally put a comma between the name and the subscript `x,[::2]`.

**Comment by aroberge** [comment]
After examining these examples further, I have concluded that they go well beyond the heuristics I use to identify the potential cause of the exceptions.  Perhaps a smarter program than Friendly-traceback might be able to handle this case...
