### ISSUE TITLE
Internal problem in Friendly-traceback. Please report this issue.

### ISSUE THREAD

**Issue by tomerv** [aroberge/friendly-traceback#181]
```
class C():
    def __str__(self):
        assert False

assert False, C()    
```

Google search finds this: https://stackoverflow.com/questions/62520310/exception-str-failed-py3

Enjoy 😉

**Comment by aroberge** [comment]
Thanks ... this is nasty! ;-)

**Comment by aroberge** [comment]
Tentative fix; first version.

```
> python -m friendly_traceback ignore.py

Warning: improperly formed exception.
I suspect that a custom exception has been raised
with a non-string value used as a message.
This can occur if a '__repr__' or a '__str__' method
is incorrectly defined.

╭──────────────────── Python exception ────────────────────╮
│ Traceback (most recent call last):                       │
│   File "ignore.py", line 5, in <module>                  │
│     assert False, C()                                    │
│ AssertionError:                                          │
│                                                          │
│ No information is available about this exception.        │
│                                                          │
│ Exception raised on line 5 of file 'ignore.py'.          │
│                                                          │
│        3:         assert False                           │
│        4:                                                │
│     -->5: assert False, C()                              │
│                                                          │
│     C: <class C> from __main__                           │
╰──────────────────────────────────────────────────────────╯
```


And, using the example code from the StackOverflow question.
```
> python -m friendly_traceback ignore.py --format=repl

Warning: improperly formed exception.
I suspect that a custom exception has been raised
with a non-string value used as a message.
This can occur if a '__repr__' or a '__str__' method
is incorrectly defined.

Traceback (most recent call last):
  File "ignore.py", line 26, in <module>
    run_me()
  File "ignore.py", line 24, in run_me
    raise MyTypeError("run_me")
MyTypeError:

    No information is available about this exception.

    Execution stopped on line 26 of file ignore.py.

       24:     raise MyTypeError("run_me")
       25:
    -->26: run_me()

            run_me: <function run_me>

    Exception raised on line 24 of file ignore.py.

       22:
       23: def run_me():
    -->24:     raise MyTypeError("run_me")

            global MyTypeError: <class MyTypeError> from __main__

```

**Comment by tomerv** [comment]
I wouldn't necessarily say that `__str__` is incorrectly defined.

For example:

```
class C():
    def __init__(self):
        self.open = False
    def __enter__(self):
        self.open = True
        return self
    def __exit__(self, a, b, c):
        self.open = False
    def __str__(self):
        assert self.open
        return "C()"  # could be something more interesting

with C() as c:
    assert False, c

```

**Comment by aroberge** [comment]
Perhaps I should add `and raises an exception.`

**Comment by aroberge** [comment]
The following is not a case of raising an exception and it still fails.
```python
class C:
    def __repr__(self):
        return None

assert False, C()
```

So, I will likely use the following:
```
Warning: improperly formed exception.
I suspect that a custom exception has been raised
with a non-string value used as a message.
This can occur if a '__repr__' or a '__str__' method
is incorrectly defined and/or raises an exception.
```
