### ISSUE TITLE
import error while running python in -OO

### ISSUE THREAD

**Issue by cdsheen** [aroberge/friendly-traceback#194]
while running python in "-OO" option

`-OO    : remove doc-strings in addition to the -O optimizations`

```
$ python -OO
Python 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import friendly_traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "..../friendly_traceback/__init__.py", line 295, in <module>
    set_include.__doc__ = set_include.__doc__.format(choices=_include_choices())
AttributeError: 'NoneType' object has no attribute 'format'
```

https://github.com/aroberge/friendly-traceback/blob/3defd0a32117bf382ebaf9dc74f171c4e11fa464/friendly/__init__.py#L301

**Comment by aroberge** [comment]
Thanks for the report. Fixed in the repo.
