### ISSUE TITLE
Error in sys.excepthook: TypeError: 'NoneType' object is not callable (fixed in master)

### ISSUE THREAD

**Issue by JulienPalard** [aroberge/friendly-traceback#98]
Got this one today with `friendly-traceback` 0.1.0 from pypi:

With `test.py` containing:
```
def isprime(a):
    return not (a < 2 or any(a % x == 0 for x in range(2, int(a ** 0.5) + 1)))


print(*[i for i in range(10000, 10051) if is_prime(i)], sep=", ")
```

I get:

```
$ python -m friendly_traceback test.py 
Error in sys.excepthook:
TypeError: 'NoneType' object is not callable

Original exception was:
Traceback (most recent call last):
  File "/home/mdk/.local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/mdk/.local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/fri/.venv/lib/python3.8/site-packages/friendly_traceback/__main__.py", line 188, in <module>
    main()
  File "/tmp/fri/.venv/lib/python3.8/site-packages/friendly_traceback/__main__.py", line 179, in main
    runpy.run_path(args.source, run_name="__main__")
  File "/home/mdk/.local/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/mdk/.local/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/mdk/.local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "test.py", line 5, in <module>
    print(*[i for i in range(10000, 10051) if is_prime(i)], sep=", ")
  File "test.py", line 5, in <listcomp>
    print(*[i for i in range(10000, 10051) if is_prime(i)], sep=", ")
NameError: name 'is_prime' is not defined
```

I do *not* have the issue with the current master, which is 8d97688a73edbfb015e1753c40b32f81c3b6fa9e.

**Comment by aroberge** [comment]
I looked at what I might have changed to fix this, but could not determine what I did.

I uploaded a new version on Pypi based on my latest version (that included a few changes that had not yet been committed prior to this bug report).

The version on Pypi should work.

**Comment by JulienPalard** [comment]
Tested it today, it works! Thanks André!
